enum Icon {
    static let addBookmark = "plus"
    static let lockPrivate = "lock"
    static let lockPublic = "lock.open"
    static let qrCode = "qrcode"
    static let qrCodePlaceholder = "square.dashed"
    static let refresh = "arrow.clockwise"
    static let browser = "safari"
    static let share = "square.and.arrow.up"
    static let tag = "tag"
    static let alert = "exclamationmark.triangle"
    static let allBookmarks = "bookmark"
    static let publicBookmarks = "person.2"
    static let privateBookmarks = "lock"
    static let unreadBookmarks = "envelope.badge"
    static let online = "cloud"
    static let clear = "xmark.circle.fill"
}
